version: '3.4'

services:
  victorifyapi:
    image: ${DOCKER_REGISTRY-}victorifyapi
    build:
      context: .
      dockerfile: VictorifyApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - victorify_network
      
  victorifydb:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - "POSTGRES_DB=VictorifyDB"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=admin"
    volumes:
      - ./.contrainers/postgres-container:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - victorify_network
 
  victorifyfrontend:
    build:
      context: ./VictorifyFrontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - victorify_network
      
  victorifyreports:
    build:
      context: ./VictorifyReports/VictorifyReports
      dockerfile: Dockerfile
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ./VictorifyReports/VictorifyReports/Reports:/app/Reports # Folder na wygenerowane raporty
    depends_on:
      - victorifyapi
    networks:
      - victorify_network
      
networks:
  victorify_network:
    driver: bridge